port: /dev/ttyUSB0
baud: 115200
rate: 20
read_rate: 60
sync_read: false
joints: {
  head_pan_joint: {type: dynamixel_wheel, id: 1, ticks: 4096, spin_on_start: false }
}

#dynamixels: {
#    head_pan_joint_foo: {id: 1}
#}

#controllers: {
#  head_controller: {type: follow_controller, joints: [head_pan_joint], action_name: head_controller/follow_joint_trajectory }
#}
